# Mine Game

`Goal`:The Character should reach the last grids 

---

`Part1` --> Detect shocked face and normal face using facial landmark detection

In [1]:
import moviepy.editor as mpy
import numpy as np
import dlib
import cv2
import winsound
import pyautogui
import time

In [2]:
def showImage(image):
    cv2.imshow('Resized Window', image)  #Display image
    cv2.waitKey(0)  #Wait for keyboard button press
    cv2.destroyAllWindows()  #Exit window and destroy all windows using

def showImageResized(image, width, height):
    cv2.namedWindow('Resized Window', cv2.WINDOW_NORMAL)  #Create window
    cv2.resizeWindow('Resized Window', width, height)  #Resize the window
    cv2.imshow('Resized Window', image)  #Display image
    cv2.waitKey(0)  #Wait for keyboard button press
    cv2.destroyAllWindows()  #Exit window and destroy all windows using

**key** is `point 36` since 'x' positions of face landmark points of shocked face is bigger than normal face. 

* detect face landmark points
* compare p36.x
* if it is smaller than 84, its normal face
* else it is shocked face

**Landmark points**

In [3]:
#The detector object is used to detect the faces given in an image. It works generally better than 
#OpenCV's default face detector
detector = dlib.get_frontal_face_detector()

#To predict the landark points given a face image, a shape predictor with a ready-to-use model
#is created. The model can be found under "http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2"
predictor = dlib.shape_predictor("shape_predictor_68_face_landmarks.dat")


### shcked face

**Compare shocked and normal face**

In [3]:
def shockedFace(img_gray):
    #The predictor only works on grayscale images

    #Use detector to find a list of rectangles containing the faces in the image. The rectangles are represented by
    #their xy coordinates
    rectangles = detector(img_gray)

    #points is a dlib structure that stores all facial landmarks points
    points = predictor(img_gray, rectangles[0])
    
    p36_x = points.part(36).x
    
    if p36_x > 84:
        return True
    else:
        return False


In [15]:
cv2.imwrite("cannyEdgeRemoved.png", edge)

True

## Edge and corner detection

In [7]:
#img = cv2.imread("test.png")
#img_gray = cv2.imread("test.png", 0)
#edge = cv2.Canny(img_gray, 100, 200)

In [35]:
#img_gray[843:, 1682:] = 170
#showImage(img_gray)

In [14]:
#showImage(edge)

In [147]:
#cv2.rectangle(img, (928,215), (990,333), (0,255,0), 1)
#showImage(img)

In [13]:
#edge[215:333, 928:990] = 0 

In [104]:
#checkedge = edge[274-10:274+10, 965-200:965+200]

In [5]:
def onEdge(img_gray, direction):
    #detect edges first 
    edge = cv2.Canny(img_gray, 100, 200)
    
    #remove the character from it
    edge[215:333, 928:990] = 0 
    
    if direction == 'x':
    
        #check if its on the edge or not
        checkedge = edge[274-10:274+10, 965-200:965+200]

        if np.count_nonzero(checkedge) == 0:
            #its edge
            return True
        else:
            return False
    elif direction == 'y': #direction is y
        #check if its on the edge or not
        checkedge = edge[274-200:274+200, 965-10:965+10]

        if np.count_nonzero(checkedge) == 0:
            #its edge
            return True
        else:
            return False

## Game

In [6]:
#initialize matrix for map
map = np.zeros((7,11), dtype=np.uint8)
#mark game area
map[1:4, 1:10] = 1
map[4:6, 1:4] = 1
map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [13]:
#we will create another matrix for mine and visit knowledge
mine_map  = np.zeros((7,11), dtype=np.uint8)
visit_map = np.zeros((7,11), dtype=np.uint8)

In [ ]:
current_point = (5,2)
initial = 0
anomaly = False

time.sleep(3)

while(True):
    
    #1 Check neighbours. Select the one that we didnt visit before and no mine
    
    up    = (current_point[0]-1, current_point[1])    #
    left  = (current_point[0]  , current_point[1]-1)
    right = (current_point[0]  , current_point[1]+1)
    down  = (current_point[0]+1, current_point[1])
    
    if anomaly:
        next_point = last_point
        #determine direction
        height = current_point[0] - last_point[0]
        width = current_point[1] - last_point[1]
        
        if height == 0 and width == 1:
            next_direction = 'left'
        if height == 0 and width == -1:
            next_direction = 'right'
        if height == 1 and width == 0:
            next_direction = 'up'
        if height == -1 and width == 0:
            next_direction = 'down'
        
        print("In Anomaly condition, heading to the ", next_direction, " direction ")
    elif (map[right] == 1 and mine_map[right] == 0 and visit_map[right] == 0 and initial != 0 and initial != 1):
        next_point = right
        next_direction = 'right'
    elif (map[up] == 1 and mine_map[up] == 0 and visit_map[up] == 0):
        next_point = up
        next_direction = 'up'
    elif (map[left] == 1 and mine_map[left] == 0 and visit_map[left] == 0):
        next_point = left
        next_direction = 'left'
    elif (map[down] == 1 and mine_map[down] == 0 and visit_map[down] == 0):
        next_point = down
        next_direction = 'down'
    else:
        next_point = last_point
        #determine direction
        
        print("Nowhere to go. Im out *-*")
        #break
        
    
    while(True):
    
        time.sleep(0.001)
        #take screenshot
        myScreenshot = pyautogui.screenshot()

        #PIL to Opencv Format
        game_image = np.array(myScreenshot)
        #Convert RGB to BGR
        game_image = cv2.cvtColor(game_image, cv2.COLOR_RGB2BGR)
        game_image_gray = cv2.cvtColor(game_image, cv2.COLOR_BGR2GRAY)
        
        #2Control screenshot. Shocked face on the right-bottom can be present.
        
        if shockedFace(game_image_gray[843:, 1682:]) and not anomaly:
            print("Shocked face detected")
            #2.a Stop moving. mark the point as mined and turn around
            mine_map[next_point] = 1
            
            
            if next_direction == 'left':
                reverse_direction = 'right'
            if next_direction == 'up':
                reverse_direction = 'down'
            if next_direction == 'right':
                reverse_direction = 'left'
            if next_direction == 'down':
                reverse_direction = 'up'
            
            #now turn around
            
            pyautogui.keyDown(reverse_direction)
            time.sleep(0.35)
            pyautogui.keyUp(reverse_direction)
            #back to step 1
            
            #game is buggy and we again need to check shocked face
            #take screenshot
            myScreenshot = pyautogui.screenshot()

            #PIL to Opencv Format
            game_image = np.array(myScreenshot)
            #Convert RGB to BGR
            game_image = cv2.cvtColor(game_image, cv2.COLOR_RGB2BGR)
            game_image_gray = cv2.cvtColor(game_image, cv2.COLOR_BGR2GRAY)
            
            if shockedFace(game_image_gray[843:, 1682:]):
                print("Anomaly detected")
                print("Current Point: ", current_point, " Last Point: ", last_point)
                anomaly = True
            
            break
        
        #2.b no shocked face. keep moving
        
        #determine direction of movement
        if next_direction == 'left' or next_direction == 'right':
            direction = 'x'
        if next_direction == 'up' or next_direction == 'down':
            direction = 'y'
        
        #character on edge
        
        if onEdge(game_image_gray, direction):
            if direction == 'y':
                movement_time = 1.35
            else:
                movement_time = 1.0
            
            pyautogui.keyDown(next_direction)
            time.sleep(movement_time)
            pyautogui.keyUp(next_direction)
            
            #mark previous point as visited
            if not anomaly:
                visit_map[current_point] = 1
            #assign next point as new current point
            last_point = current_point
            current_point = next_point
            
            anomaly = False
            print("current point", current_point)
            #back to step 1
            break

        #print(onEdge(game_image_gray, 'y'))

        #press left keyfor 0.3 seconds    
        pyautogui.keyDown(next_direction)
        time.sleep(0.1)
        pyautogui.keyUp(next_direction)
        #pyautogui.press("left", interval=0.5)
    
    if current_point == (1,9) or current_point == (2,9) or current_point == (3,9):
        print("___WIN___")
        break
    initial += 1
    

Shocked face detected
current point (5, 1)
current point (4, 1)
current point (3, 1)
current point (3, 2)
Shocked face detected
current point (2, 2)
current point (2, 3)
current point (2, 4)
Shocked face detected
Shocked face detected
current point (3, 4)


In [21]:
mine_map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [22]:
visit_map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)